#ifndef AIXOS_VERSION_H
#define AIXOS_VERSION_H

#define AIXOS_VERSION_MAJOR        1u
#define AIXOS_VERSION_MINOR        0u
#define AIXOS_VERSION_PATCH        0u
#define AIXOS_CRASH_RECORD_VERSION 5u
#define AIXOS_API_VERSION          0x00010000u
#define AIXOS_ABI_VERSION          0x00010000u

#define AIXOS_STRINGIFY_INNER(value) #value
#define AIXOS_STRINGIFY(value)       AIXOS_STRINGIFY_INNER(value)
#define AIXOS_VERSION_STRING \
    AIXOS_STRINGIFY(AIXOS_VERSION_MAJOR) "." \
    AIXOS_STRINGIFY(AIXOS_VERSION_MINOR) "." \
    AIXOS_STRINGIFY(AIXOS_VERSION_PATCH)

#ifndef AIXOS_BUILD_ID
#define AIXOS_BUILD_ID 0u
#endif

#endif
