#ifndef AIXOS_USER_CFG_H
#define AIXOS_USER_CFG_H

/*
 * User-tunable configuration generated by `make config`.
 * Edit manually only when an automated/menu flow is not available.
 */

#ifndef AIXOS_CFG_PROFILE_MINIMAL
#define AIXOS_CFG_PROFILE_MINIMAL       0
#endif

#define AIXOS_CFG_SCHED_BITMAP          1
#define AIXOS_CFG_SCHED_SIMPLE          2
#ifndef AIXOS_CFG_SCHEDULER
#define AIXOS_CFG_SCHEDULER             AIXOS_CFG_SCHED_BITMAP
#endif

#ifndef AIXOS_CFG_TRACE_ENABLE
#define AIXOS_CFG_TRACE_ENABLE          1
#endif
#ifndef AIXOS_CFG_ENABLE_SIGNALS
#define AIXOS_CFG_ENABLE_SIGNALS        1
#endif
#ifndef AIXOS_CFG_ENABLE_NAMESPACE
#define AIXOS_CFG_ENABLE_NAMESPACE      1
#endif
#ifndef AIXOS_CFG_ENABLE_TIME_WHEEL
#define AIXOS_CFG_ENABLE_TIME_WHEEL     1
#endif
#ifndef AIXOS_CFG_ENABLE_PANIC_RESET
#define AIXOS_CFG_ENABLE_PANIC_RESET    1
#endif
#ifndef AIXOS_CFG_ENABLE_MPU
#define AIXOS_CFG_ENABLE_MPU            1
#endif

#ifndef AIXOS_CFG_MAX_PRIORITY
#define AIXOS_CFG_MAX_PRIORITY          256
#endif
#ifndef AIXOS_CFG_HEAP_SIZE
#define AIXOS_CFG_HEAP_SIZE             (7 * 1024)
#endif
#ifndef AIXOS_CFG_TIME_SLICE_TICKS
#define AIXOS_CFG_TIME_SLICE_TICKS      1
#endif

#endif /* AIXOS_USER_CFG_H */
