#!/usr/bin/env python3
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / "config" / "aixos_user_cfg.h"


ITEMS = [
    ("AIXOS_CFG_PROFILE_MINIMAL", "Minimal profile", "bool"),
    ("AIXOS_CFG_SCHEDULER", "Scheduler backend", "sched"),
    ("AIXOS_CFG_TRACE_ENABLE", "Trace recorder", "bool"),
    ("AIXOS_CFG_ENABLE_MPU", "MPU/user memory protection", "bool"),
    ("AIXOS_CFG_ENABLE_TIME_WHEEL", "Hierarchical timeout wheel", "bool"),
    ("AIXOS_CFG_ENABLE_NAMESPACE", "Resource namespace", "bool"),
    ("AIXOS_CFG_ENABLE_SIGNALS", "Task signals", "bool"),
    ("AIXOS_CFG_ENABLE_PANIC_RESET", "Panic reset hook", "bool"),
    ("AIXOS_CFG_MAX_PRIORITY", "Priority levels", "int"),
    ("AIXOS_CFG_HEAP_SIZE", "Heap size bytes", "heap"),
    ("AIXOS_CFG_TIME_SLICE_TICKS", "Round-robin time slice ticks", "int"),
]

DEFAULTS = {
    "AIXOS_CFG_PROFILE_MINIMAL": "0",
    "AIXOS_CFG_SCHEDULER": "AIXOS_CFG_SCHED_BITMAP",
    "AIXOS_CFG_TRACE_ENABLE": "1",
    "AIXOS_CFG_ENABLE_MPU": "1",
    "AIXOS_CFG_ENABLE_TIME_WHEEL": "1",
    "AIXOS_CFG_ENABLE_NAMESPACE": "1",
    "AIXOS_CFG_ENABLE_SIGNALS": "1",
    "AIXOS_CFG_ENABLE_PANIC_RESET": "1",
    "AIXOS_CFG_MAX_PRIORITY": "256",
    "AIXOS_CFG_HEAP_SIZE": "(7 * 1024)",
    "AIXOS_CFG_TIME_SLICE_TICKS": "1",
}


def load():
    values = dict(DEFAULTS)
    if CFG.exists():
        text = CFG.read_text()
        for key in values:
            match = re.search(rf"^\s*#define\s+{key}\s+(.+?)\s*$",
                              text, re.MULTILINE)
            if match:
                values[key] = match.group(1).strip()
    return values


def write(values):
    text = [
        "#ifndef AIXOS_USER_CFG_H",
        "#define AIXOS_USER_CFG_H",
        "",
        "/*",
        " * User-tunable configuration generated by `make config`.",
        " * Edit manually only when an automated/menu flow is not available.",
        " */",
        "",
        "#ifndef AIXOS_CFG_PROFILE_MINIMAL",
        f"#define AIXOS_CFG_PROFILE_MINIMAL       {values['AIXOS_CFG_PROFILE_MINIMAL']}",
        "#endif",
        "",
        "#define AIXOS_CFG_SCHED_BITMAP          1",
        "#define AIXOS_CFG_SCHED_SIMPLE          2",
        "#ifndef AIXOS_CFG_SCHEDULER",
        f"#define AIXOS_CFG_SCHEDULER             {values['AIXOS_CFG_SCHEDULER']}",
        "#endif",
        "",
        "#ifndef AIXOS_CFG_TRACE_ENABLE",
        f"#define AIXOS_CFG_TRACE_ENABLE          {values['AIXOS_CFG_TRACE_ENABLE']}",
        "#endif",
        "#ifndef AIXOS_CFG_ENABLE_SIGNALS",
        f"#define AIXOS_CFG_ENABLE_SIGNALS        {values['AIXOS_CFG_ENABLE_SIGNALS']}",
        "#endif",
        "#ifndef AIXOS_CFG_ENABLE_NAMESPACE",
        f"#define AIXOS_CFG_ENABLE_NAMESPACE      {values['AIXOS_CFG_ENABLE_NAMESPACE']}",
        "#endif",
        "#ifndef AIXOS_CFG_ENABLE_TIME_WHEEL",
        f"#define AIXOS_CFG_ENABLE_TIME_WHEEL     {values['AIXOS_CFG_ENABLE_TIME_WHEEL']}",
        "#endif",
        "#ifndef AIXOS_CFG_ENABLE_PANIC_RESET",
        f"#define AIXOS_CFG_ENABLE_PANIC_RESET    {values['AIXOS_CFG_ENABLE_PANIC_RESET']}",
        "#endif",
        "#ifndef AIXOS_CFG_ENABLE_MPU",
        f"#define AIXOS_CFG_ENABLE_MPU            {values['AIXOS_CFG_ENABLE_MPU']}",
        "#endif",
        "",
        "#ifndef AIXOS_CFG_MAX_PRIORITY",
        f"#define AIXOS_CFG_MAX_PRIORITY          {values['AIXOS_CFG_MAX_PRIORITY']}",
        "#endif",
        "#ifndef AIXOS_CFG_HEAP_SIZE",
        f"#define AIXOS_CFG_HEAP_SIZE             {values['AIXOS_CFG_HEAP_SIZE']}",
        "#endif",
        "#ifndef AIXOS_CFG_TIME_SLICE_TICKS",
        f"#define AIXOS_CFG_TIME_SLICE_TICKS      {values['AIXOS_CFG_TIME_SLICE_TICKS']}",
        "#endif",
        "",
        "#endif /* AIXOS_USER_CFG_H */",
        "",
    ]
    CFG.write_text("\n".join(text))


def label(key, kind, value):
    if kind == "bool":
        return "enabled" if value != "0" else "disabled"
    if kind == "sched":
        return "bitmap multi-queue" if value == "AIXOS_CFG_SCHED_BITMAP" else "simple sorted list"
    return value


def toggle(values, key, kind):
    if kind == "bool":
        values[key] = "0" if values[key] != "0" else "1"
    elif kind == "sched":
        values[key] = ("AIXOS_CFG_SCHED_SIMPLE"
                       if values[key] == "AIXOS_CFG_SCHED_BITMAP"
                       else "AIXOS_CFG_SCHED_BITMAP")
    elif kind == "heap":
        raw = input("Heap size in bytes (or expression, e.g. 4096): ").strip()
        if raw:
            values[key] = raw
    else:
        raw = input(f"{key} value: ").strip()
        if raw:
            values[key] = raw


def show(values):
    print("\nAIXOS v1.0 configuration")
    print("=" * 30)
    for idx, (key, name, kind) in enumerate(ITEMS, 1):
        print(f"{idx:2d}. {name:<34} {label(key, kind, values[key])}")
    print("\nCommands: number=change, s=save, q=quit without saving, d=defaults")


def main(argv):
    values = load()
    if len(argv) > 1 and argv[1] == "--show":
        show(values)
        return 0
    if len(argv) > 1 and argv[1] == "--defaults":
        write(dict(DEFAULTS))
        print(f"wrote defaults to {CFG}")
        return 0

    while True:
        show(values)
        choice = input("> ").strip().lower()
        if choice == "s":
            write(values)
            print(f"saved {CFG}")
            return 0
        if choice == "q":
            print("configuration unchanged")
            return 0
        if choice == "d":
            values = dict(DEFAULTS)
            continue
        if choice.isdigit() and 1 <= int(choice) <= len(ITEMS):
            key, _name, kind = ITEMS[int(choice) - 1]
            toggle(values, key, kind)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
